### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by aharpervc** [jitbit/HtmlSanitizer#1]
Given that this code is heavily inspired by [this SO answer](https://stackoverflow.com/a/28533511), and that code from SO is licensed as [CC BY-SA 3.0](https://stackoverflow.com/help/licensing) and requires attribution, should the license for this library change? Probably to CC-BY-SA 3.0 as well?

**Comment by alex-jitbit** [comment]
Indeed it is, seems tag whitelisting borrows a lot from that answer. We'll include a proper attribution as per https://stackoverflow.blog/2009/06/25/attribution-required/

**Comment by aharpervc** [comment]
That's fine, but the real problem is the license. I don't know if GPLv3 is compatible with CC BY SA 3.0, but I do know that that makes it basically impossible to use for commercial apps. Would you consider changing the license for this library or dual licensing it as CC BY SA 3.0?

**Comment by alex-jitbit** [comment]
Yes, sure. @aharpervc will do that later today
