### ISSUE TITLE
Performance issue with many images

### ISSUE THREAD

**Issue by alethiophile** [jitbit/HtmlSanitizer#15]
When sanitizing HTML that contains many image tags, this code wants to load all the images (presumably due to loading them into the DOM). This makes it actually a good deal slower than a pure-JS solution like sanitize-html.

I don't know if there's actually anything you can do about this (maybe you can turn off image loading for the iframe in question?)

**Comment by alex-jitbit** [comment]
Even though the images are being loaded, the browser does this asynchronously, so it should not affect the speed... The frame is then killed and image load is aborted.

**Comment by alethiophile** [comment]
While that's a very nice theory, in practice using HtmlSanitizer pegs my CPU and makes the fan scream for minutes on end, and sanitize-html doesn't.

**Comment by alex-jitbit** [comment]
I'm currently rewriting it without iframes, using `DOMParser` will release an update shortly. Watch out for this issue to be closed
