### ISSUE TITLE
license question in js file

### ISSUE THREAD

**Issue by RTFaught** [jitbit/HtmlSanitizer#3]
I see the license file is for MIT, but the HtmlSanitizer.js file still says:
//License: GNU GPL v3 https://github.com/jitbit/HtmlSanitizer/blob/master/LICENSE
perhaps you want to make them match?

Thanks for posting your work.

**Comment by alex-jitbit** [comment]
Fixed in eff4209095d3e2ed629c443a3f95905dcd3c9573
