### ISSUE TITLE
Possible to whitelist any data attributes?

### ISSUE THREAD

**Issue by ianchouinard** [jitbit/HtmlSanitizer#6]
Trying to sanitize a small bit of html which includes data attributes that is built based on a JSON response from a 3rd party API. 

Is there a way to whitelist any data attributes ex: (data-{attribute-name}), or do I need to add all data attributes I have to the attributes whitelist?

**Comment by alex-jitbit** [comment]
There's no way to whitelist all data attributes at once like `data-*` currently the only to do that would be to add all of them to the white list.
