### ISSUE TITLE
Produces error when the first node / root container is not whitelisted

### ISSUE THREAD

**Issue by bbottema** [jitbit/HtmlSanitizer#8]
I get the following error:
```
ERROR TypeError: Cannot read property 'replace' of undefined
    at Object.HtmlSanitizer.SanitizeHtml (HtmlSanitizer.js:92)
```
The line number might be incorrect by one as I rermoved the log statement in the top.
```html
var resultElement = makeSanitizedCopy(iframedoc.body);
document.body.removeChild(iframe);
return resultElement.innerHTML
	.replace(/<br[^>]*>(\S)/g, "<br>\n$1")
	.replace(/div><div/g, "div>\n<div"); //replace is just for cleaner code
```
resultElement is not null, but the `.innerHTML` property doesn't exist here. Debugging in Chrome shows that resultElement is of type `#document-fragment`, which doesn't have a innerHTML property.

It happened because the script went into the else statement of makeSanitzedCopy() for the first node:
```
			} else {
				newNode = document.createDocumentFragment();
			}
```
I'm guessing that because I empties all the whitelists and only left in my custom tags. The html that goes into it starts with <html> or somthine which is not white listed anymore.

**Comment by alex-jitbit** [comment]
can't replicate this on the latest version. Can you provide a test that replicates this? (see tests.html for examples)
