### ISSUE TITLE
Adding input to iframe flagged by Veracode as XSS flaw

### ISSUE THREAD

**Issue by qxx** [jitbit/HtmlSanitizer#9]
We were using HtmlSanitizer.js for XSS protection in the front end. But in a recent scan Veracode is flagging the sanitizer itself as an XSS flaw, specifically L44 where it's sending the input to the sandbox iframe. 

https://github.com/jitbit/HtmlSanitizer/blob/eff4209095d3e2ed629c443a3f95905dcd3c9573/HtmlSanitizer.js#L44

So I'm wondering, is setting `iframe['sandbox'] = 'allow-same-origin';` sufficient to prevent the iframe itself becoming vulnerable so that I can tell Veracode "I know that, it's safe"?

**Comment by alex-jitbit** [comment]
Yes, a sandboxed iframe is not allowed to execute any JS, submit forms, etc.
